In [46]:
import pandas as pd
import numpy as np


In [47]:
# Loading in the dataset and doing an initial check
df = pd.read_csv('rentfaster.csv')

df.head()
df.shape
df.columns
df.info()
df.describe()
df.sample(n=5, random_state=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25771 entries, 0 to 25770
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   rentfaster_id      25771 non-null  int64  
 1   city               25771 non-null  object 
 2   province           25771 non-null  object 
 3   address            25646 non-null  object 
 4   latitude           25771 non-null  float64
 5   longitude          25771 non-null  float64
 6   lease_term         25725 non-null  object 
 7   type               25771 non-null  object 
 8   price              25771 non-null  float64
 9   beds               25639 non-null  object 
 10  baths              25637 non-null  object 
 11  sq_feet            21659 non-null  object 
 12  link               25771 non-null  object 
 13  furnishing         25771 non-null  object 
 14  availability_date  25759 non-null  object 
 15  smoking            23069 non-null  object 
 16  cats               255

rentfaster_id      city province                     address  \
13024         570328   Calgary  Alberta              Herron Walk NE   
4691          569598   Calgary  Alberta  25 Walgrove Walk Southeast   
37            563675   Airdrie  Alberta        171 Baneberry Way SW   
24693         315466  Montréal   Quebec            520 rue de Gaspé   
20992         383122   Toronto  Ontario           44 Lillian Street   

        latitude   longitude lease_term       type   price    beds baths  \
13024  51.190039 -114.052503  Long Term   Basement  1300.0   1 Bed     1   
4691   50.866188 -114.027240  Long Term  Apartment  2200.0  2 Beds     2   
37     51.292034 -114.050214  12 months      House  2800.0  3 Beds   2.5   
24693  45.456078  -73.548578  Long Term  Apartment  1449.0   1 Bed     1   
20992  43.705655  -79.393608  Long Term  Apartment  3525.0  2 Beds     2   

      sq_feet                                               link   furnishing  \
13024     600  /ab/calgary/rentals/basement/1-bedroom/livings...  Unfurnished   
4691     1100  /ab/calgary/rentals/apartment/2-bedrooms/walde...  Unfurnished   
37       2100  /ab/airdrie/rentals/house/3-bedrooms/non-smoki...  Unfurnished   
24693     750  /qc/montreal/rentals/apartment/1-bedroom/pet-f...  Unfurnished   
20992     828  /on/toronto/rentals/apartment/1-bedroom/pet-fr...  Unfurnished   

           availability_date      smoking   cats   dogs  
13024                July 01  Non-Smoking   True  False  
4691   Call for Availability  Non-Smoking  False  False  
37                 Immediate  Non-Smoking  False  False  
24693              August 01  Non-Smoking   True   True  
20992                July 31  Non-Smoking   True   True

In [48]:
# Checking for null values
df.isnull().sum()

# Removing the null values
df.dropna(inplace=True)
df.isnull().sum()

rentfaster_id        0
city                 0
province             0
address              0
latitude             0
longitude            0
lease_term           0
type                 0
price                0
beds                 0
baths                0
sq_feet              0
link                 0
furnishing           0
availability_date    0
smoking              0
cats                 0
dogs                 0
dtype: int64

In [49]:
# Dropping duplicate rows
df.drop_duplicates(inplace=True)

In [50]:
# Checking what values are in the 'beds' column
df['beds'].unique()

array(['2 Beds', '3 Beds', 'Studio', '1 Bed', '5 Beds', '4 Beds',
       '6 Beds', '8 Beds', '7 Beds', '9 Beds'], dtype=object)

In [51]:
# Removing strings from beds column
df['beds'] = df['beds'].str.replace('Bed', '')
df['beds'] = df['beds'].str.replace('s', '')
df['beds'] = df['beds'].str.replace('Studio', '0')
df['beds'] = df['beds'].str.replace(' ', '')

df['beds'].unique()

array(['2', '3', '0', '1', '5', '4', '6', '8', '7', '9'], dtype=object)

In [52]:
# Converting beds column to numeric (int) and checking for any non-numeric values
df['beds'] = pd.to_numeric(df['beds'], errors='coerce')
df['beds'].unique()

array([2, 3, 0, 1, 5, 4, 6, 8, 7, 9])

In [53]:
df.sample(n=5, random_state=1)

rentfaster_id            city          province  \
22803         508616  Côte Saint-Luc            Quebec   
3432          406910         Calgary           Alberta   
14871         569577        Victoria  British Columbia   
4276          530963         Calgary           Alberta   
5388          437811        Edmonton           Alberta   

                      address   latitude   longitude lease_term       type  \
22803  5885 Ave. Marc Chagall  45.480288  -73.663982  Long Term  Apartment   
3432   323 5 Avenue Northeast  51.056884 -114.056342  Long Term  Apartment   
14871           45 Gorge Rd E  48.443404 -123.387582  Long Term  Apartment   
4276                  Tuscany  51.130770 -114.254658  Long Term      House   
5388           8122 106 ST NW  53.517723 -113.503495  Long Term  Apartment   

        price  beds baths sq_feet  \
22803  2450.0     2     1    1005   
3432   1625.0     1     1     578   
14871  3100.0     2     2     841   
4276   4100.0     5   3.5    2400   
5388   1719.0     1     1     635   

                                                    link   furnishing  \
22803  /qc/c-te-saint-luc/rentals/apartment/1-bedroom...  Unfurnished   
3432   /ab/calgary/rentals/apartment/1-bedroom/cresce...  Unfurnished   
14871  /bc/victoria/rentals/apartment/1-bedroom/domin...  Unfurnished   
4276   /ab/calgary/rentals/house/5-bedrooms/tuscany/p...  Unfurnished   
5388   /ab/edmonton/rentals/apartment/1-bedroom/old-s...  Unfurnished   

      availability_date      smoking   cats   dogs  
22803           July 01  Non-Smoking   True   True  
3432         No Vacancy  Non-Smoking  False  False  
14871         Immediate  Non-Smoking   True   True  
4276          August 01  Non-Smoking   True   True  
5388          Immediate  Non-Smoking   True   True

In [54]:
# Dropping unnecessary columns
df.drop(columns=['link', 'furnishing', 'cats', 'dogs', 'availability_date'], inplace=True)
df.sample(n=5, random_state=1)

rentfaster_id            city          province  \
22803         508616  Côte Saint-Luc            Quebec   
3432          406910         Calgary           Alberta   
14871         569577        Victoria  British Columbia   
4276          530963         Calgary           Alberta   
5388          437811        Edmonton           Alberta   

                      address   latitude   longitude lease_term       type  \
22803  5885 Ave. Marc Chagall  45.480288  -73.663982  Long Term  Apartment   
3432   323 5 Avenue Northeast  51.056884 -114.056342  Long Term  Apartment   
14871           45 Gorge Rd E  48.443404 -123.387582  Long Term  Apartment   
4276                  Tuscany  51.130770 -114.254658  Long Term      House   
5388           8122 106 ST NW  53.517723 -113.503495  Long Term  Apartment   

        price  beds baths sq_feet      smoking  
22803  2450.0     2     1    1005  Non-Smoking  
3432   1625.0     1     1     578  Non-Smoking  
14871  3100.0     2     2     841  Non-Smoking  
4276   4100.0     5   3.5    2400  Non-Smoking  
5388   1719.0     1     1     635  Non-Smoking

In [55]:
# Checking smoking column values
df['smoking'].unique()


array(['Non-Smoking', 'Smoke Free Building', 'Negotiable',
       'Smoking Allowed'], dtype=object)

In [56]:
# Removing unwanted values from smoking column
df = df.drop(df[df['smoking'] == 'Negotiable'].index)
df = df.drop(df[df['smoking'] == 'Smoking Allowed'].index)

df['smoking'].unique()

array(['Non-Smoking', 'Smoke Free Building'], dtype=object)

In [57]:
# Dropping unnecessary columns
df.drop(columns=['smoking'], inplace=True)
df.sample(n=5, random_state=1)

rentfaster_id        city      province                   address  \
1125          367078     Calgary       Alberta  2304 26 Avenue Northwest   
20594         376808     Toronto       Ontario      25 Montgomery Avenue   
5832          554875    Edmonton       Alberta         11009 109A Avenue   
25545         407642   Saskatoon  Saskatchewan   111 111 St W, Saskatoon   
8816          334193  Wetaskiwin       Alberta          3901-3933 54A St   

        latitude   longitude lease_term        type   price  beds baths  \
1125   51.076323 -114.113219  Long Term  Main Floor  2000.0     3     1   
20594  43.709298  -79.399749  Long Term   Apartment  3894.0     2     2   
5832   53.555480 -113.511683  Long Term   Apartment  2095.0     2     2   
25545  52.139496 -106.601068  Long Term   Apartment  1375.0     2     1   
8816   52.958335 -113.385347  Long Term   Townhouse  1299.0     2     1   

      sq_feet  
1125      950  
20594     963  
5832      983  
25545     732  
8816      870

In [58]:
df['type'].unique()

array(['Townhouse', 'Apartment', 'Main Floor', 'Basement', 'House',
       'Condo Unit', 'Room For Rent', 'Duplex', 'Loft', 'Vacation Home',
       'Acreage', 'Mobile'], dtype=object)

In [59]:
# Removing unwanted values from type column
df = df.drop(df[df['type'] == 'Mobile'].index)
df = df.drop(df[df['type'] == 'Vacation Home'].index)
df = df.drop(df[df['type'] == 'Acreage'].index)

df['type'].unique()

array(['Townhouse', 'Apartment', 'Main Floor', 'Basement', 'House',
       'Condo Unit', 'Room For Rent', 'Duplex', 'Loft'], dtype=object)

In [60]:
df['baths'].unique()

array(['2.5', '1', '2', '1.5', '3.5', '4', '3', '5', 'none', '4.5', '7.5',
       '5.5', '6', '6.5', '0', '7'], dtype=object)

In [61]:
# Removing unwanted values from baths column (e.g., 'none')
df = df.drop(df[df['baths'] == 'none'].index)
df['baths'].unique()

array(['2.5', '1', '2', '1.5', '3.5', '4', '3', '5', '4.5', '7.5', '5.5',
       '6', '6.5', '0', '7'], dtype=object)

In [62]:
# Converting baths column to numeric (int)
df['baths'] = pd.to_numeric(df['baths'], errors='coerce')
df['baths'].unique()

array([2.5, 1. , 2. , 1.5, 3.5, 4. , 3. , 5. , 4.5, 7.5, 5.5, 6. , 6.5,
       0. , 7. ])

In [63]:
# Removing unwanted values from baths column (e.g., 0)
df = df.drop(df[df['baths'] == 0].index)
df['baths'] = df['baths'].astype(int)
df['baths'].unique()

array([2, 1, 3, 4, 5, 7, 6])

In [64]:
# Checking for 0's in the 'price' column
df.loc[df['price'] == 0]


rentfaster_id             city          province  \
700           417846          Calgary           Alberta   
4788          359534          Calgary           Alberta   
5039          393635          Calgary           Alberta   
8931          330276          Burnaby  British Columbia   
8932          330276          Burnaby  British Columbia   
8944          330277          Burnaby  British Columbia   
9136          539597          Kelowna  British Columbia   
9450          330250  New Westminster  British Columbia   
15397         536861         Winnipeg          Manitoba   
15402         536861         Winnipeg          Manitoba   
15405         536861         Winnipeg          Manitoba   
15406         536861         Winnipeg          Manitoba   
15416         537670         Winnipeg          Manitoba   
15423         537670         Winnipeg          Manitoba   
15547         537870         Winnipeg          Manitoba   
15549         537870         Winnipeg          Manitoba   
15550         537870         Winnipeg          Manitoba   
15561         537627         Winnipeg          Manitoba   
15567         537627         Winnipeg          Manitoba   
15574         537627         Winnipeg          Manitoba   
15576         537627         Winnipeg          Manitoba   
15578         537627         Winnipeg          Manitoba   
19212         501288           Ottawa           Ontario   
19213         501288           Ottawa           Ontario   
20670         338362          Toronto           Ontario   
20671         338362          Toronto           Ontario   
20672         338362          Toronto           Ontario   
20673         338362          Toronto           Ontario   
20708         343048          Toronto           Ontario   
20709         343048          Toronto           Ontario   
20710         343048          Toronto           Ontario   
20711         343048          Toronto           Ontario   
20712         343048          Toronto           Ontario   
20756         343050          Toronto           Ontario   
22012         572130          Toronto           Ontario   
22049         450786          Toronto           Ontario   
22201         336176          Toronto           Ontario   
22253         330218          Toronto           Ontario   
24354         536449         Montréal            Quebec   
24615         536448         Montréal            Quebec   

                        address   latitude   longitude lease_term       type  \
700               919 10 Ave SW  51.043534 -114.082819  Long Term  Apartment   
4788               515 4 Ave NE  51.055763 -114.051664  Long Term  Townhouse   
5039                880 9 St SE  51.042895 -114.038907  Long Term  Apartment   
8931        9500 Erickson Drive  49.252106 -122.901224  Long Term  Apartment   
8932        9500 Erickson Drive  49.252106 -122.901224  Long Term  Apartment   
8944          9304 Salish Court  49.251366 -122.901811  Long Term  Apartment   
9136        1975 Dilworth Drive  49.879775 -119.436881  Long Term  Apartment   
9450       737 Carnarvon Street  49.202722 -122.911832  Long Term  Apartment   
15397          160 Smith Street  49.889664  -97.140109  Long Term  Apartment   
15402          160 Smith Street  49.889664  -97.140109  Long Term  Apartment   
15405          160 Smith Street  49.889664  -97.140109  Long Term  Apartment   
15406          160 Smith Street  49.889664  -97.140109  Long Term  Apartment   
15416        33 Hargrave Street  49.891942  -97.144063  Long Term  Apartment   
15423        33 Hargrave Street  49.891942  -97.144063  Long Term  Apartment   
15547                  70 Garry  49.886486  -97.136916  Long Term  Apartment   
15549                  70 Garry  49.886486  -97.136916  Long Term  Apartment   
15550                  70 Garry  49.886486  -97.136916  Long Term  Apartment   
15561       525 St. Mary Avenue  49.889531  -97.152365  Long Term  Apartment   
15567       525 St. Mary Avenue  49.889531  -97.152365  Long Term  

In [65]:
# Removing unwanted values from the 'price' column
df = df.drop(df[df['price'] == 0].index)

In [66]:
# Making sure all the 0's in the 'price' column were removed
df.loc[df['price'] == 0]

Empty DataFrame
Columns: [rentfaster_id, city, province, address, latitude, longitude, lease_term, type, price, beds, baths, sq_feet]
Index: []

In [67]:
# Cheking for any other outliers in the 'price' column
df.loc[df['price'] < 500]

rentfaster_id             city          province  \
6190         571804         Edmonton           Alberta   
9417         400910  New Westminster  British Columbia   

                        address   latitude   longitude lease_term       type  \
6190  6125 17A Avenue Northwest  53.446943 -113.431219  Long Term      House   
9417           321 Agnes Street  49.206943 -122.906835  Long Term  Apartment   

      price  beds  baths sq_feet  
6190    1.0     6      2    1600  
9417  250.0     0      1     160

In [68]:
# Removing unwanted values from the 'price' column
df = df.drop(df[df['price'] < 500].index)

In [69]:
df.sample(n=5, random_state=1)

rentfaster_id      city province                        address  \
18499         559539    Ottawa  Ontario              265 Rideau Street   
24230         354062  Montréal   Quebec        360 René-Lévesque Ouest   
16600         442937   Chatham  Ontario                12 Dufferin Ave   
5118          567494   Camrose  Alberta             4920 66th St. #100   
3065          571722   Calgary  Alberta  33 Setonstone Green Southeast   

        latitude   longitude lease_term       type   price  beds  baths  \
18499  45.428846  -75.686676  Long Term  Apartment  2675.0     2      2   
24230  45.505576  -73.564211  Long Term  Apartment  1910.0     1      1   
16600  42.401383  -82.181943  Long Term  Apartment  1500.0     2      1   
5118   53.020655 -112.858134  Long Term  Apartment  1365.0     2      1   
3065   50.868687 -113.945776  Long Term   Basement  1550.0     2      1   

      sq_feet  
18499     918  
24230     685  
16600    1284  
5118      800  
3065      700

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13886 entries, 0 to 25770
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   rentfaster_id  13886 non-null  int64  
 1   city           13886 non-null  object 
 2   province       13886 non-null  object 
 3   address        13886 non-null  object 
 4   latitude       13886 non-null  float64
 5   longitude      13886 non-null  float64
 6   lease_term     13886 non-null  object 
 7   type           13886 non-null  object 
 8   price          13886 non-null  float64
 9   beds           13886 non-null  int64  
 10  baths          13886 non-null  int64  
 11  sq_feet        13886 non-null  object 
dtypes: float64(3), int64(3), object(6)
memory usage: 1.4+ MB


In [71]:
df['sq_feet'].unique()

array(['1403', '1496', '1180', ..., '260', '286', '334'], dtype=object)

In [72]:
# Converting baths column to numeric (int)
df['sq_feet'] = pd.to_numeric(df['sq_feet'], errors='coerce')
df['sq_feet'].unique()

array([1403., 1496., 1180., ...,  260.,  286.,  334.])

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13886 entries, 0 to 25770
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   rentfaster_id  13886 non-null  int64  
 1   city           13886 non-null  object 
 2   province       13886 non-null  object 
 3   address        13886 non-null  object 
 4   latitude       13886 non-null  float64
 5   longitude      13886 non-null  float64
 6   lease_term     13886 non-null  object 
 7   type           13886 non-null  object 
 8   price          13886 non-null  float64
 9   beds           13886 non-null  int64  
 10  baths          13886 non-null  int64  
 11  sq_feet        13630 non-null  float64
dtypes: float64(4), int64(3), object(5)
memory usage: 1.4+ MB


In [74]:
df['lease_term'].unique()

array(['Long Term', 'Negotiable', 'Short Term', '12 months', 'months',
       '6 months'], dtype=object)

In [75]:
# Renaming values in lease_term column
df['lease_term'] = df['lease_term'].str.replace('12 months', '1 year')
df['lease_term'] = df['lease_term'].str.replace('6 months', '0.5 year')
df['lease_term'] = df['lease_term'].str.replace('months', 'Month to Month')

df['lease_term'].unique()

array(['Long Term', 'Negotiable', 'Short Term', '1 year',
       'Month to Month', '0.5 year'], dtype=object)

In [76]:
# Final check (checking for null values again)

df.isnull().sum()

rentfaster_id      0
city               0
province           0
address            0
latitude           0
longitude          0
lease_term         0
type               0
price              0
beds               0
baths              0
sq_feet          256
dtype: int64

In [77]:
df.dtypes

rentfaster_id      int64
city              object
province          object
address           object
latitude         float64
longitude        float64
lease_term        object
type              object
price            float64
beds               int64
baths              int64
sq_feet          float64
dtype: object

In [78]:
# Checking for negative values in the price column
df[df["price"] < 0]

Empty DataFrame
Columns: [rentfaster_id, city, province, address, latitude, longitude, lease_term, type, price, beds, baths, sq_feet]
Index: []

In [79]:
# Exporting the cleaned dataset to a new CSV file
df.to_csv('rentfaster_cleaned.csv', index=False)